name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Install dependencies & build
        run: |
          yarn install
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
